#/usr/bin/bash
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToAnoCar2.bed ~/Work/Annotation/liftOver_chain_file/anoCar2ToHg38.over.chain.gz Table_human_organoid_unified_peaks_anoCar2ToHg38.bed unmapped_anoCar2ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToCalJac4.bed ~/Work/Annotation/liftOver_chain_file/calJac4ToHg38.over.chain.gz Table_human_organoid_unified_peaks_calJac4ToHg38.bed unmapped_calJac4ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToDanRer11.bed ~/Work/Annotation/liftOver_chain_file/danRer11ToHg38.over.chain.gz Table_human_organoid_unified_peaks_danRer11ToHg38.bed unmapped_danRer11ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToGalGal6.bed ~/Work/Annotation/liftOver_chain_file/galGal6ToHg38.over.chain.gz Table_human_organoid_unified_peaks_galGal6ToHg38.bed unmapped_galGal6ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToGasAcu1.bed ~/Work/Annotation/liftOver_chain_file/gasAcu1ToHg38.over.chain.gz Table_human_organoid_unified_peaks_gasAcu1ToHg38.bed unmapped_gasAcu1ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToGorGor6.bed ~/Work/Annotation/liftOver_chain_file/gorGor6ToHg38.over.chain.gz Table_human_organoid_unified_peaks_gorGor6ToHg38.bed unmapped_gorGor6ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToMm10.bed ~/Work/Annotation/liftOver_chain_file/mm10ToHg38.over.chain.gz Table_human_organoid_unified_peaks_mm10ToHg38.bed unmapped_mm10ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToPanTro6.bed ~/Work/Annotation/liftOver_chain_file/panTro6ToHg38.over.chain.gz Table_human_organoid_unified_peaks_panTro6ToHg38.bed unmapped_panTro6ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToRheMac10.bed ~/Work/Annotation/liftOver_chain_file/rheMac10ToHg38.over.chain.gz Table_human_organoid_unified_peaks_rheMac10ToHg38.bed unmapped_rheMac10ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToRn7.bed ~/Work/Annotation/liftOver_chain_file/rn7ToHg38.over.chain.gz Table_human_organoid_unified_peaks_rn7ToHg38.bed unmapped_rn7ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToTupBel1.bed ~/Work/Annotation/liftOver_chain_file/tupBel1ToHg38.over.chain.gz Table_human_organoid_unified_peaks_tupBel1ToHg38.bed unmapped_tupBel1ToHg38.bed -minMatch=0.1
~/Work/Tools/liftOver Table_human_organoid_unified_peaks_hg38ToXenTro10.bed ~/Work/Annotation/liftOver_chain_file/xenTro10ToHg38.over.chain.gz Table_human_organoid_unified_peaks_xenTro10ToHg38.bed unmapped_xenTro10ToHg38.bed -minMatch=0.1
